name: github_trending
description: Project that shows trending projects on github

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  intl: ^0.17.0
  url_launcher: ^6.1.4
  shimmer: ^2.0.0
  cached_network_image: ^3.2.1
  dropdown_search: ^5.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
